./build/compiler test/array.c 3
./build/compiler test/array.c 4
./build/compiler test/branch.c 3
./build/compiler test/branch.c 4
./build/compiler test/circle.c 3
./build/compiler test/circle.c 4
./build/compiler test/func.c 3
./build/compiler test/func.c 4
./build/compiler test/operation.c 3
./build/compiler test/operation.c 4